### PR TITLE
More better class child style

### PR DESCRIPTION
**Pull request by rtlechow**
The extra indentation from nested child class style is kinda icky.

### CODE REVIEW

**Review by hoganmark — APPROVED** [review]

**Review by SCR-TON — APPROVED** [review]

**Comment by granth** [comment]
I don't think we should change this. It's one of Ruby's weird things that they're not exactly the same thing: https://rubystyle.guide/#namespace-definition

Where is the code that you dislike nesting?

**Comment by rtlechow** [comment]
@granth https://github.com/4ormat/4ormat/pull/10426/checks?check_run_id=608897683

**Comment by granth** [comment]
Ok. So you want to use namespaces constants like `Workflow::Contact` as whole names all the time, rather than ever referring to `Contact` within `Workflow`? It's certainly more greppable. 🤔

**Comment by granth** [comment]
I think we should be consistent, either way. With this change there are `497 issues to fix` in https://github.com/4ormat/4ormat/pull/10432

**Comment by mferrier** [comment]
my two cents: in my experience the compact style breaks things sometimes in dev mode, but that might not be an issue anymore. iirc it was "expected <path> to define class Foo" errors.

**Comment by rtlechow** [comment]
K, reverted https://github.com/4ormat/styleguide/pull/16

fwiw, the compact-style Workflow code was all produced by the Rails generator.

**Comment by granth** [comment]
Oh, interesting. A built-in generator?

**Comment by rtlechow** [comment]
Yep, i.e. `rails g scaffold workflow/project…`

**Comment by granth** [comment]
Hmm. Old issue: https://github.com/rails/rails/issues/25772

To be clear, I don't _love_ the extra indentation. 😐

**Pull request merged**
